stages:
  data_collection:
    cmd: python -m src.data.data_collection
    deps:
    - src/data/data_collection.py
    params:
    - data_collection.test_size
    outs:
    - data/raw
  data_process:
    cmd: python -m src.data.data_processing
    deps:
    - data/raw
    - src/data/data_processing.py
    outs:
    - data/processed
  model_build:
    cmd: python -m src.model.model_building
    deps:
    - data/processed
    - src/data/data_collection.py
    - src/model/model_building.py
    params:
    - model_building.n_estimators
    outs:
    - models/model.pkl


  model_eval:
    cmd: python src/model/model_evaluation.py
    deps:
    - models/model.pkl
    - src/model/model_evaluation.py
    outs:
    - reports/run_info.json
    metrics:
    - reports/metrics.json

  model_registration:
    # cmd: bash -c "python src/model/model_registry.py $MODEL_STAGE"
    cmd: bash -c "python src/model/model_registry.py staging
    deps:
    - reports/metrics.json
    - src/model/model_registry.py
