name: Delploy MLFLOW using github

on:
  push:
    branches:
     - master


  workflow_dispatch:
    inputs:
      model_stage:
        description: "Choose model stage"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production
          - archive
          - promote
          - list

jobs:
  mlfow-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install dvc

      - name: Run DVC pipeline
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
          MODEL_STAGE: ${{ github.event.inputs.model_stage }}
        run: |
          dvc repro
